version: 0.2

phases:
  pre_build:
    commands:
      - yarn
  build:
    commands:
      # - yarn build
      - npm run-script build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build