version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      - echo Building ...
      - yarn build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build